export const DEFAULT_PIC = 'https://cdn2.iconfinder.com/data/icons/social-flat-buttons-3/512/anonymous-512.png'
export const BASE_URL = 'http://localhost:4002/'
export const DEFAULT_COVER_PIC = 'https://w0.peakpx.com/wallpaper/410/412/HD-wallpaper-plain-black-black.jpg'
export const DEFAULT_PRIVATE_PIC = 'https://cdn4.iconfinder.com/data/icons/users-69/64/Artboard_15-512.png'
export const DEFAULT_PUBLIC_PIC = 'https://cdn4.iconfinder.com/data/icons/users-69/64/Artboard_16-512.png'